### ISSUE TITLE
create mintable 721 contract called NiftyVault

### ISSUE THREAD

**Issue by cupOJoseph** [UseKeyp/od-contracts#14]
- Mintable function can be called by SafeManager to create a new safe and mints a new NFT with SAFEid = nft id
- set SafeManager address during deployment once
- update deployment scripts to set SafeManager address
- permissioned setter for updating SafeManager address that can only be updated by the DAO address
- import openzeppelin 721
- added to Proxy Registry and renaming the contract Vault721

testing
- minting can only be called by authorized address

**Comment by hking2** [comment]
mint = create safe

**Comment by daopunk** [comment]
pushed to arby branch

**Comment by cupOJoseph** [comment]
closed in #11
