### ISSUE TITLE
Update all foundry tests to interact with the proxy registry / Vault721 contract instead of a DSProxy

### ISSUE THREAD

**Issue by cupOJoseph** [UseKeyp/od-contracts#21]
HUGE

go through _EVERY SINGLE TEST_ in the automated fuzzing tests and unit tests to update where the end user calls get routed through to the rest of the SAFE engine. 

- testing on new transfer functions via NFTs
- basic NFT tests for new features
- passing linter tests
- updated safe transfer tests that hit the safe manager

**Comment by wei3erHase** [comment]
gotta create a file under `test/scopes/NewProxy.t.s` and add each of the proxy interactions, then import the e2e adding a test contract (at the end of e2es) that looks like:
```solidity
contract E2ETestWithMyProxy is MyProxy, CommonTest, ... {}
```
