### ISSUE TITLE
Token naming

### ISSUE THREAD

**Issue by cupOJoseph** [UseKeyp/od-contracts#4]
https://github.com/UseKeyp/opendollar/blob/0957d053a31d805630cb59c56b454522579d31dc/src/script/Common.s.sol#L182

replace KITE with OPEN

**Comment by hking2** [comment]
remote: Permission to UseKeyp/opendollar.git denied to hking2.
fatal: unable to access 'https://github.com/UseKeyp/opendollar.git/': The requested URL returned error: 403

**Comment by hking2** [comment]
also, are there standard settings that i should use to avoid arbitrary changes around print-width, etc. that i should add to my VScode?

**Comment by pi0neerpat** [comment]
Governance token name: ODG
Protocol token name: OD
