### ISSUE TITLE
license everything openly in package.json too

### ISSUE THREAD

**Issue by cupOJoseph** [UseKeyp/od-contracts#9]

**Comment by hking2** [comment]
`  
  "name": "hai",
  "version": "0.0.1",
  "private": true,
  "description": "Multicollateral ETH backed stablecoin",
  "homepage": "https://github.com/hai-on-op/hai#readme",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hai-on-op/hai.git"
  },
  "license": "MIT",
  "author": "Wonderland",
  "contributors": [
    "wei3erHase (https://github.com/wei3erHase)",
    "0xGorilla (https://github.com/0xGorilla)",
    "0xJabberwock (https://github.com/0xJabberwock)",
    "0xRaccoon (https://github.com/0xRaccoon)"
  ],`

should we update contributors, homepage, name, etc?

**Comment by cupOJoseph** [comment]
>contributors, homepage, name, etc?

Yep, let's clean it up and get it ready for public release

**Comment by hking2** [comment]
author = keyp
github = individuals

**Comment by pi0neerpat** [comment]
Close per Josephs rec
